### ISSUE TITLE
Clean up py side of compiler

### ISSUE THREAD

**Issue by bdemann** [demergent-labs/kybra#377] opened 2023-05-09 15:26 UTC
same as https://github.com/demergent-labs/azle/issues/1017 but for python

- [ ] Format all Python errors in the rust format
    - [ ] Write a simple rust program that takes in the errors and calls the annotate snippets library.
- [ ] Get colors to actually work (from the Rust side too)

**Comment by dansteren** [comment] 2023-06-26 16:02
Duplicate of #277

**Closed as completed** 2023-06-26 16:04 UTC
Labels: duplicate, code cleanliness
